[project]
name = "wrangler-python-tester"
version = "0.1.0"
description = "(Cloudflare Python Worker) and excel"
requires-python = ">=3.12"
dependencies = ["openpyxl==3.1.5"]

[dependency-groups]
dev = ["workers-py"]